image: Visual Studio 2019

configuration: Release

install:
  - ps: |
      nuget restore Source/RetryableAssertions.sln
      dotnet restore Source/

build:
  project: Source/RetryableAssertions.sln
  publish_nuget: true
  verbosity: minimal

test: off

deploy:
  - provider: NuGet
    api_key:
      secure: gKLEfhlRtIFnS9joCT9oqAMx3MC7JArdfpfQlEBocObFG4qigbKJpmGMNtvVCtQ7
    skip_symbols: true
    on:
      branch: /^master$/
